jq "[.data.children[].data | select(.created_utc>$lastCheck)]" $rawInputFile > $filteredInputFile


length=$(jq '. | length' $filteredInputFile)

	echo $filteredInputFile
for x in $(seq 0 $(($length - 1))); do
	noP=$(jq ".[$x].body" $filteredInputFile | ./count-paren.sh)
	emoticonResp=$(jq ".[$x].body" $filteredInputFile | grep -o ':(' | sed 's/[()]//g')
	echo "$noP"
	if [ $noP -gt 0 ]; then
		./post-comment.sh \
			"$(jq -r ".[$x].name" $filteredInputFile)" \
"$emoticonResp$(printf ')%.0s' $(seq 1 $noP))

---
This is an autogenerated response. [source](https://github.com/hugonikanor/reddit-parenthesis-bot) | /u/HugoNikanor" \
		&& echo "posted" \
		|| echo "failed"
	fi
done
